### ISSUE TITLE
Option for DNS resolution failure handling

### ISSUE THREAD

**Issue by darkfader** [chirpstack/chirpstack-packet-multiplexer#6]
It seems to stop when DNS resolve fails for one of the backends. Perhaps just continue and print and error in the log?
As a side-note, I wonder how DNS changes are propagating between lets say a chirpstack docker and a packet-multiplexer docker.

**Comment by brocaar** [comment]
I believe the latest commit fixes the DNS resolve failure, as it now resolves once an uplink is received from a gateway that passes the filter list (or if the list is empty). An error is printed when the configured host can't be resolved / connected.
